"""
pdf_report_generator.py — Javelin Motion Analysis PDF Report Generator

Generates a structured PDF report from job data (job.json + report.json +
representative frames + graph images) using ReportLab.

Usage:
    from src.pdf_report_generator import generate_pdf_report_for_job
    pdf_path = generate_pdf_report_for_job(Path("jobs/20260508_181930_c4bd"))
    # -> Path("jobs/20260508_181930_c4bd/report/report.pdf")
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.lib.utils import ImageReader
from reportlab.platypus import (
    Flowable,
    HRFlowable,
    Image,
    KeepTogether,
    NextPageTemplate,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.frames import Frame
from reportlab.platypus.doctemplate import PageTemplate, BaseDocTemplate

logger = logging.getLogger(__name__)

# ── 定数 ──────────────────────────────────────────────────────────────────────

PAGE_W, PAGE_H = A4           # 595.27 x 841.89 pt
MARGIN_L = 2.0 * cm
MARGIN_R = 2.0 * cm
MARGIN_T = 2.0 * cm
MARGIN_B = 2.0 * cm
CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R

BRAND_BLUE   = colors.HexColor("#1A4D8F")
BRAND_ORANGE = colors.HexColor("#E86A2E")
LIGHT_GRAY   = colors.HexColor("#F5F5F5")
MID_GRAY     = colors.HexColor("#CCCCCC")
TEXT_DARK    = colors.HexColor("#1A1A1A")

# ── スタイル ──────────────────────────────────────────────────────────────────

def _make_styles() -> dict:
    base = getSampleStyleSheet()

    def s(name, **kw) -> ParagraphStyle:
        return ParagraphStyle(name, **kw)

    return {
        "cover_title": s(
            "CoverTitle",
            fontName="Helvetica-Bold",
            fontSize=28,
            textColor=BRAND_BLUE,
            spaceAfter=6,
            alignment=TA_CENTER,
        ),
        "cover_subtitle": s(
            "CoverSubtitle",
            fontName="Helvetica",
            fontSize=13,
            textColor=BRAND_ORANGE,
            spaceAfter=2,
            alignment=TA_CENTER,
        ),
        "cover_date": s(
            "CoverDate",
            fontName="Helvetica",
            fontSize=10,
            textColor=colors.grey,
            alignment=TA_CENTER,
        ),
        "section_heading": s(
            "SectionHeading",
            fontName="Helvetica-Bold",
            fontSize=14,
            textColor=BRAND_BLUE,
            spaceBefore=12,
            spaceAfter=4,
        ),
        "body": s(
            "Body",
            fontName="Helvetica",
            fontSize=10,
            textColor=TEXT_DARK,
            spaceAfter=2,
            leading=14,
        ),
        "body_sm": s(
            "BodySm",
            fontName="Helvetica",
            fontSize=9,
            textColor=colors.grey,
            spaceAfter=1,
            leading=13,
        ),
        "caption": s(
            "Caption",
            fontName="Helvetica-Oblique",
            fontSize=8,
            textColor=colors.grey,
            alignment=TA_CENTER,
            spaceAfter=4,
        ),
        "disclaimer": s(
            "Disclaimer",
            fontName="Helvetica",
            fontSize=9,
            textColor=TEXT_DARK,
            spaceAfter=6,
            leading=14,
            alignment=TA_LEFT,
        ),
        "label": s(
            "Label",
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=TEXT_DARK,
            spaceAfter=2,
        ),
        "kv_key": s(
            "KVKey",
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=BRAND_BLUE,
        ),
        "kv_val": s(
            "KVVal",
            fontName="Helvetica",
            fontSize=10,
            textColor=TEXT_DARK,
        ),
    }


# ── ヘッダー・フッター描画 ─────────────────────────────────────────────────────

def _draw_header_footer(canvas, doc):
    canvas.saveState()
    # ヘッダー
    canvas.setFillColor(BRAND_BLUE)
    canvas.rect(0, PAGE_H - 1.2 * cm, PAGE_W, 1.2 * cm, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.drawString(MARGIN_L, PAGE_H - 0.8 * cm, "Javelin Motion Analysis Report")
    canvas.setFont("Helvetica", 9)
    canvas.drawRightString(PAGE_W - MARGIN_R, PAGE_H - 0.8 * cm, doc.title or "")
    # フッター
    canvas.setFillColor(MID_GRAY)
    canvas.rect(0, 0, PAGE_W, 1.0 * cm, fill=1, stroke=0)
    canvas.setFillColor(colors.grey)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(MARGIN_L, 0.35 * cm,
                      "Generated by Javelin Video Analysis  |  Not for medical use")
    canvas.drawRightString(PAGE_W - MARGIN_R, 0.35 * cm,
                           f"Page {doc.page}")
    canvas.restoreState()


def _draw_cover_footer(canvas, doc):
    """表紙のフッターはシンプル版"""
    canvas.saveState()
    canvas.setFillColor(BRAND_ORANGE)
    canvas.rect(0, 0, PAGE_W, 0.5 * cm, fill=1, stroke=0)
    canvas.restoreState()


# ── ユーティリティ ────────────────────────────────────────────────────────────

def _load_json(path: Path) -> Optional[dict]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _format_dt(dt_str: Optional[str]) -> str:
    if not dt_str:
        return "—"
    try:
        return datetime.fromisoformat(dt_str).strftime("%Y-%m-%d  %H:%M:%S")
    except Exception:
        return dt_str


def _scale_image(img_path: Path, max_w: float, max_h: float) -> tuple[float, float]:
    """画像を最大サイズに収まるようにアスペクト比を保ちリサイズ。"""
    try:
        ir = ImageReader(str(img_path))
        iw, ih = ir.getSize()
        scale = min(max_w / iw, max_h / ih, 1.0)
        return iw * scale, ih * scale
    except Exception:
        return max_w, max_w * 0.5


def _kv_table(pairs: list[tuple[str, str]], styles: dict) -> Table:
    """キー・バリューペアの2列テーブルを生成。"""
    data = [[Paragraph(k, styles["kv_key"]), Paragraph(v, styles["kv_val"])]
            for k, v in pairs]
    col_w = [CONTENT_W * 0.38, CONTENT_W * 0.62]
    tbl = Table(data, colWidths=col_w, hAlign="LEFT")
    tbl.setStyle(TableStyle([
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [LIGHT_GRAY, colors.white]),
        ("TOPPADDING",    (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 6),
        ("GRID",          (0, 0), (-1, -1), 0.25, MID_GRAY),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return tbl


def _hr(styles: dict) -> List:
    return [Spacer(1, 4), HRFlowable(width=CONTENT_W, color=MID_GRAY), Spacer(1, 4)]


# ── ページビルダー関数 ────────────────────────────────────────────────────────

def _build_cover(job: dict, rep: dict, styles: dict) -> List:
    story = []
    story.append(Spacer(1, 4.0 * cm))
    story.append(Paragraph("Javelin Motion Analysis", styles["cover_title"]))
    story.append(Paragraph("Report", styles["cover_title"]))
    story.append(Spacer(1, 0.6 * cm))
    story.append(HRFlowable(width=CONTENT_W * 0.5, color=BRAND_ORANGE,
                             hAlign="CENTER", thickness=2))
    story.append(Spacer(1, 0.6 * cm))

    job_id = job.get("job_id", "—")
    story.append(Paragraph(f"Job ID: {job_id}", styles["cover_subtitle"]))
    story.append(Spacer(1, 0.3 * cm))

    created  = _format_dt(job.get("created_at"))
    updated  = _format_dt(job.get("updated_at"))
    story.append(Paragraph(f"Created:  {created}", styles["cover_date"]))
    story.append(Paragraph(f"Updated:  {updated}", styles["cover_date"]))
    story.append(Spacer(1, 2.0 * cm))

    # メタ情報グリッド
    input_file = job.get("input_file", "—")
    input_name = Path(input_file).name if input_file else "—"
    height_m   = job.get("height_m")
    height_str = f"{height_m:.2f} m" if height_m else "—"

    pairs = [
        ("Status",      str(job.get("status", "—")).capitalize()),
        ("Mode",        str(job.get("mode", "—"))),
        ("Height",      height_str),
        ("Input video", input_name),
    ]
    story.append(_kv_table(pairs, styles))
    story.append(PageBreak())
    return story


def _build_analysis_summary(job: dict, rep: dict, report_dir: Path, styles: dict) -> List:
    story = []
    story.append(Paragraph("Analysis Summary", styles["section_heading"]))
    story.extend(_hr(styles))

    analysis = rep.get("analysis", {})
    video_info = rep.get("video_info", {})

    # 動画情報
    story.append(Paragraph("Video Information", styles["label"]))
    vid_pairs: list[tuple[str, str]] = [
        ("Resolution",  f"{video_info.get('width', '—')} × {video_info.get('height', '—')} px"),
        ("FPS",         str(video_info.get("fps", "—"))),
        ("Total frames",str(video_info.get("total_frames", "—"))),
        ("Duration",    f"{video_info.get('duration_s', '—')} s"),
    ]
    story.append(_kv_table(vid_pairs, styles))
    story.append(Spacer(1, 0.4 * cm))

    # 解析結果
    if analysis:
        story.append(Paragraph("Pose Analysis Metrics", styles["label"]))
        ana_pairs: list[tuple[str, str]] = [
            ("Height (m)",              f"{analysis.get('height_m', '—')}"),
            ("Calibrated",              str(analysis.get("calibrated", "—"))),
            ("Pose detected frames",    str(analysis.get("pose_detected_frames", "—"))),
            ("Pose detection rate",     f"{analysis.get('pose_detection_rate', '—'):.0%}"
                                        if isinstance(analysis.get("pose_detection_rate"), float)
                                        else str(analysis.get("pose_detection_rate", "—"))),
            ("Wrist max speed (km/h)",  str(analysis.get("wrist_max_speed_kmh", "—"))),
            ("Wrist mean speed (km/h)", str(analysis.get("wrist_mean_speed_kmh", "—"))),
            ("Release speed (km/h)",    str(analysis.get("release_speed_kmh", "—"))),
        ]
        story.append(_kv_table(ana_pairs, styles))
        story.append(Spacer(1, 0.4 * cm))

    # ファイル有無サマリ
    story.append(Paragraph("Output File Summary", styles["label"]))
    frames_dir  = report_dir / "frames"
    graphs_dir  = report_dir / "graphs"
    csv_path    = report_dir / "pose_landmarks.csv"
    frame_count = len(list(frames_dir.glob("*.jpg")) + list(frames_dir.glob("*.png"))) \
                  if frames_dir.exists() else 0
    graph_count = len(list(graphs_dir.glob("*.png"))) if graphs_dir.exists() else 0

    mp4_list  = [f for f in job.get("output_files", []) if str(f).endswith(".mp4")]

    summary_pairs: list[tuple[str, str]] = [
        ("Output videos",         f"{len(mp4_list)} file(s)"),
        ("pose_landmarks.csv",    "✓ Present" if csv_path.exists() else "✗ Not found"),
        ("Representative frames", f"{frame_count} image(s)"),
        ("Graph images",          f"{graph_count} image(s)"),
    ]
    story.append(_kv_table(summary_pairs, styles))
    story.append(Spacer(1, 0.4 * cm))

    # 出力動画ファイル一覧
    if mp4_list:
        story.append(Paragraph("Output Video Files", styles["label"]))
        for mp4 in mp4_list:
            story.append(Paragraph(f"  • {Path(mp4).name}", styles["body_sm"]))

    story.append(PageBreak())
    return story


def _build_frames_pages(report_dir: Path, styles: dict,
                        images_per_page: int = 4) -> List:
    story = []
    story.append(Paragraph("Representative Frames", styles["section_heading"]))
    story.extend(_hr(styles))

    frames_dir = report_dir / "frames"
    frame_imgs: List[Path] = []
    if frames_dir.exists():
        frame_imgs = sorted(frames_dir.glob("*.jpg")) + sorted(frames_dir.glob("*.png"))

    if not frame_imgs:
        story.append(Paragraph("No representative frames found.", styles["body"]))
        story.append(PageBreak())
        return story

    # 1ページに images_per_page 枚（2列×2行）
    max_img_h = (PAGE_H - MARGIN_T - MARGIN_B - 3.0 * cm) / 2 - 1.2 * cm
    max_img_w = (CONTENT_W - 0.4 * cm) / 2

    for i in range(0, len(frame_imgs), images_per_page):
        chunk = frame_imgs[i: i + images_per_page]
        # 2列のテーブルで配置
        rows = []
        captions = []
        for j in range(0, len(chunk), 2):
            row_imgs = chunk[j: j + 2]
            row_cells = []
            cap_cells = []
            for img_path in row_imgs:
                w, h = _scale_image(img_path, max_img_w, max_img_h)
                try:
                    img = Image(str(img_path), width=w, height=h)
                    row_cells.append(img)
                    cap_cells.append(Paragraph(img_path.name, styles["caption"]))
                except Exception:
                    row_cells.append(Paragraph("(image load error)", styles["body_sm"]))
                    cap_cells.append(Paragraph("", styles["caption"]))
            # 2列揃え
            while len(row_cells) < 2:
                row_cells.append("")
                cap_cells.append("")
            rows.append(row_cells)
            captions.append(cap_cells)

        tbl_data = []
        for img_row, cap_row in zip(rows, captions):
            tbl_data.append(img_row)
            tbl_data.append(cap_row)

        col_w = [CONTENT_W / 2, CONTENT_W / 2]
        tbl = Table(tbl_data, colWidths=col_w, hAlign="CENTER")
        tbl.setStyle(TableStyle([
            ("ALIGN",       (0, 0), (-1, -1), "CENTER"),
            ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING",  (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ]))
        story.append(tbl)

        if i + images_per_page < len(frame_imgs):
            story.append(PageBreak())

    story.append(PageBreak())
    return story


def _build_graphs_pages(report_dir: Path, styles: dict,
                        images_per_page: int = 2) -> List:
    story = []
    story.append(Paragraph("Analysis Graphs", styles["section_heading"]))
    story.extend(_hr(styles))

    graphs_dir = report_dir / "graphs"
    graph_imgs: List[Path] = []
    if graphs_dir.exists():
        graph_imgs = sorted(graphs_dir.glob("*.png"))

    if not graph_imgs:
        story.append(Paragraph("No graph images found.", styles["body"]))
        story.append(PageBreak())
        return story

    max_img_h = (PAGE_H - MARGIN_T - MARGIN_B - 3.0 * cm) / images_per_page - 1.2 * cm
    max_img_w = CONTENT_W * 0.95

    for i, img_path in enumerate(graph_imgs):
        w, h = _scale_image(img_path, max_img_w, max_img_h)
        try:
            img = Image(str(img_path), width=w, height=h)
            cap = Paragraph(img_path.stem.replace("_", " ").title(), styles["caption"])
            story.append(KeepTogether([img, cap]))
        except Exception:
            story.append(Paragraph(f"(Could not load: {img_path.name})", styles["body_sm"]))

        story.append(Spacer(1, 0.5 * cm))

        # images_per_page ごとにページブレーク
        if (i + 1) % images_per_page == 0 and i + 1 < len(graph_imgs):
            story.append(PageBreak())

    story.append(PageBreak())
    return story


def _build_disclaimer(styles: dict) -> List:
    story = []
    story.append(Paragraph("Notes & Disclaimer", styles["section_heading"]))
    story.extend(_hr(styles))
    story.append(Spacer(1, 0.4 * cm))

    disclaimer_lines = [
        "This report is generated automatically from pose estimation data "
        "obtained through computer vision processing.",
        "",
        "This is <b>not</b> a medical diagnosis or professional coaching diagnosis. "
        "The data presented in this report should not be used as the sole basis "
        "for medical, training, or rehabilitation decisions.",
        "",
        "Pose estimation accuracy may vary depending on camera angle, video quality, "
        "subject occlusion, lighting conditions, and clothing. "
        "Estimated metrics (speeds, angles, trajectories) may include measurement errors.",
        "",
        "Please use this report as a visual reference and supplementary data summary "
        "alongside qualified professional assessment.",
        "",
        f"Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "Software: Javelin Video Analysis  |  Engine: MediaPipe Pose",
    ]
    for line in disclaimer_lines:
        story.append(Paragraph(line if line else "&nbsp;", styles["disclaimer"]))

    return story


# ── メインエントリポイント ────────────────────────────────────────────────────

def generate_pdf_report_for_job(job_dir: Path) -> Path:
    """
    job_dir 配下のデータを読み込み、A4 PDF レポートを生成して返す。

    Parameters
    ----------
    job_dir : Path
        ジョブルートディレクトリ (例: jobs/20260508_181930_c4bd)

    Returns
    -------
    Path
        生成された PDF のパス (job_dir/report/report.pdf)

    Raises
    ------
    RuntimeError
        PDF 生成に失敗した場合
    """
    job_dir = Path(job_dir)
    report_dir = job_dir / "report"
    report_dir.mkdir(parents=True, exist_ok=True)

    # データ読み込み
    job_json_path = job_dir / "job.json"
    job: dict = _load_json(job_json_path) or {}

    # report.json は複数ある場合があるため最新を使用
    rep_json_files = sorted(
        (job_dir / "output").glob("*_report.json")
    ) if (job_dir / "output").exists() else []
    rep_json_path = report_dir / "report.json"

    rep: dict = {}
    if rep_json_path.exists():
        rep = _load_json(rep_json_path) or {}
    elif rep_json_files:
        rep = _load_json(rep_json_files[-1]) or {}

    styles = _make_styles()

    # ストーリー組み立て
    story: List = []
    story.extend(_build_cover(job, rep, styles))
    story.extend(_build_analysis_summary(job, rep, report_dir, styles))
    story.extend(_build_frames_pages(report_dir, styles, images_per_page=4))
    story.extend(_build_graphs_pages(report_dir, styles, images_per_page=2))
    story.extend(_build_disclaimer(styles))

    # PDF 出力
    pdf_path = report_dir / "report.pdf"
    job_id = job.get("job_id", job_dir.name)

    doc = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4,
        leftMargin=MARGIN_L,
        rightMargin=MARGIN_R,
        topMargin=MARGIN_T + 1.2 * cm,   # ヘッダー分
        bottomMargin=MARGIN_B + 1.0 * cm, # フッター分
        title=job_id,
        author="Javelin Video Analysis",
        subject="Motion Analysis Report",
    )

    try:
        doc.build(story, onFirstPage=_draw_cover_footer,
                  onLaterPages=_draw_header_footer)
    except Exception as e:
        raise RuntimeError(f"PDF build failed: {e}") from e

    logger.info(f"[pdf_report_generator] PDF saved: {pdf_path}")
    return pdf_path
